# Generated by Django 5.0.6 on 2024-07-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default-profile-img.png', upload_to='profile_images'),
        ),
    ]
