# Generated by Django 5.0.6 on 2024-07-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_img',
            field=models.ImageField(default='default_background_img.jpg', upload_to='background_images'),
        ),
    ]
