# Generated by Django 5.0.6 on 2024-09-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_of_likes',
        ),
    ]
